### ISSUE TITLE
Infinite loop in mother tracker

### ISSUE THREAD

**Issue by jaxoncreed** [solid/mashlib#28] opened 2019-06-05 23:52 UTC
The infinite loop problem in the mother tracker is happening again
After some testing I have confirmed that it happens in `mashlib 0.7.19` but not in `mashlib 0.7.18`

Here is the diff between the two of them for your reference: https://github.com/solid/mashlib/compare/master@%7B03-18-19%7D...master

I have already tried and confirmed that it is NOT only due to the upgrade to `rdflib 0.20.1` from `rdflib 0.19.1`

It could be partially due to that, but simply downgrading rdflib on mashlib 0.7.19 did not fix the problem

Unfortunately, the data that replicates this problem is very private, so maybe myself and tim are the only ones who can debug this.

**Comment by Vinnl** [comment] 2019-06-06 07:42
@jaxoncreed You mentioned elsewhere that this was caused by a bug in rdflib - can I close this, and should this still be reported there?

**Closed** 2019-06-10 14:31 UTC
